# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Category.create([
  {name: "Roll and Move", desc: "Rolling dice, spinning a wheel or drawing cards are what allow the players to make their move.", examples: "Clue, Monopoly, Candy land, The Game of Life"},
  {name: "Strategic Placement", desc: "Strategic placement games are usually played slower and with more strategy, planning your moves to ultimately dominate the board.", examples: "Ticket to ride, Sequence, Lord of Waterdeep, Champions of Midgard, Rajas of the Ganges"},
  {name: "Cooperative", desc: "Its all about team work. Players work together to acheve a comeon goal, wining the game.", examples: "Pandamic, Castle Panic, Forbidden Island"},
  {name: "Secret Identity", desc: "Desception is the name of the game. Forgeting who you are and taking in your game character as yourself.", examples: "Mafia, Coup, Secret Hitler, One Night Ultimate Werewolf"},
])

Game.create([
  {title: "Sequence", description: "Sequence is a board and card game, the players compete to create rows, columns or diagonals of 5 connected checkers placed on the cards that the player has laid down.", number_of_players: 12, category_id: 2},
  {title: "Risk", description: "The goal is conquest of the world.", number_of_players: 6, category_id: 2},
  {title: "Ticket To Ride: Europe", description: "Ticket to Ride: Europe takes you on a new train adventure across Europe. From Edinburgh to Constantinople and from Lisbon to Moscow, you'll visit great cities of turn-of-the-century Europe", number_of_players: 5, category_id: 2},
  {title: "Pandamic", description: "In Pandemic, several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures for each of four plagues before they get out of hand.", number_of_players: 4, category_id: 3},
  {title: "Wingspan", description: "Wingspan is a competitive, medium-weight, card-driven, engine-building board game from Stonemaier Games. It's designed by Elizabeth Hargrave and features over 170 birds illustrated by Natalia Rojas and Ana Maria Martinez.", number_of_players: 5, category_id: 1},
  {title: "Gloomhaven", description: "Gloomhaven is a game of Euro-inspired tactical combat in a persistent world of shifting motives. Players will take on the role of a wandering adventurer with their own special set of skills and their own reasons for traveling to this dark corner of the world.", number_of_players: 4, category_id: 2},
  {title: "Brass: Birmingham", description: "Brass Birmingham is an economic strategy game sequel to Martin Wallace 2007 masterpiece, Brass. Birmingham tells the story of competing entrepreneurs in Birmingham during the industrial revolution, between the years of 1770-1870.", number_of_players: 4, category_id: 2},
  {title: "Terraforming Mars", description: "In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable.", number_of_players: 5, category_id: 3},
  {title: "Twilight Imperium (Fourth Edition)", description: "Twilight Imperium (Fourth Edition) is a game of galactic conquest in which three to six players take on the role of one of seventeen factions vying for galactic domination through military might, political maneuvering, and economic bargaining.", number_of_players: 6, category_id: 2},
  {title: "Ultimate Werewolf: Deluxe Edition", description: "One of the most popular social deductions games of all time, Ultimate Werewolf takes the familiar homebrewed rules of the game Mafia and refines them into addicting gameplay.", number_of_players: 20, category_id: 4},
  {title: "The Game of Life", description: "", number_of_players: , category_id: 1},
  {title: "Codenames", description: "Codenames is an easy party game to solve puzzles.
    The game is divided into red and blue, each side has a team leader, the team leader's goal is to lead their team to the final victory.", number_of_players: 8, category_id: 3},
  {title: "Candy Land", description: "Players race down a rainbow-colored track to be the first to find the lost King Kandy at Candy Castle, but watch out for obstacles like the sticky Molasses Swamp!", number_of_players: 4, category_id: 1},
  {title: "Monopoly", description: "Players take the part of land owners, attempting to buy and then develop their land. Income is gained by other players visiting their properties and money is spent when they visit properties belonging to other players. When times get tough, players may have to mortgage their properties to raise cash for fines, taxes and other misfortunes.", number_of_players: 8, category_id: 1},
  {title: "Battleship", description: "Each player deploys his ships (of lengths varying from 2 to 5 squares) secretly on a square grid. Then each player shoots at the other's grid by calling a location. The defender responds by 'Hit!' or 'Miss!'. You try to deduce where the enemy ships are and sink them. First to do so wins.", number_of_players: 2, category_id: 2},
  {title: "Blokus", description: "Blokus (officially pronounced 'Block us') is an abstract strategy game with transparent, Tetris-shaped, colored pieces that players are trying to play onto the board. The only caveat to placing a piece is that it may not lie adjacent to your other pieces, but instead must be placed touching at least one corner of your pieces already on the board.", number_of_players: 4, category_id: 2},
  {title: "Apples to Apples", description: "The party game Apples to Apples consists of two decks of cards: Things and Descriptions. Each round, the active player draws a Description card (which features an adjective like 'Hairy' or 'Smarmy') from the deck, then the other players each secretly choose the Thing card in hand that best matches that description and plays it face-down on the table. The active player then reveals these cards and chooses the Thing card that, in his opinion, best matches the Description card, which he awards to whoever played that Thing card. This player becomes the new active player for the next round.", number_of_players: 10, category_id: 1},
  {title: "Catan", description: "In CATAN (formerly The Settlers of Catan), players try to be the dominant force on the island of Catan by building settlements, cities, and roads. On each turn dice are rolled to determine what resources the island produces.", number_of_players: 4, category_id: 1},
  {title: "Azul", description: "As a tile-laying artist, you have been challenged to embellish the walls of the Royal Palace of Evora. In the game Azul, players take turns drafting colored tiles from suppliers to their player board. Later in the round, players score points based on how they've placed their tiles to decorate the palace.", number_of_players: 4, category_id: 2 }
])